In [1]:
#SKALA
import cv2

# Membaca gambar
img = cv2.imread('d:\\Data Kuliah\\Citra Digital - Semester 5\\images2.jpeg')

# Mengubah ukuran gambar
dstSkala = cv2.resize(img, None, fx=2.5, fy=2, interpolation=cv2.INTER_CUBIC)

# Menampilkan gambar asli
cv2.imshow('Original Image', img)

# Menampilkan gambar yang telah diubah ukurannya
cv2.imshow('Resized Image', dstSkala)

# Menunggu tombol ditekan dan menutup semua jendela
cv2.waitKey(0)
cv2.destroyAllWindows()


IMG = 

In [2]:
#Translasi
import cv2
import numpy as np

img = cv2.imread("d:\\Data Kuliah\\Citra Digital - Semester 5\\images2.jpeg")
print(img.shape)

baris, coloms, ghgh = img.shape

MTranslasi = np.float32([[2, 0, 100],[0, 2, 50]])

print(MTranslasi, '\n')

dst = cv2.warpAffine (img, MTranslasi, (coloms, baris))
cv2.imshow('title', dst)

cv2.waitKey(0)
cv2.destroyAllWindows()

(259, 194, 3)
[[  2.   0. 100.]
 [  0.   2.  50.]] 



In [7]:
# rotasi
import cv2

img = cv2.imread("d:\\Data Kuliah\\Citra Digital - Semester 5\\images2.jpeg")
baris, coloms, ghgh = img.shape

MRotasi = cv2.getRotationMatrix2D((coloms/2, baris/2), 90, 1)

print(MRotasi)

dstRotasi = cv2.warpAffine(img, MRotasi, (coloms, baris))

cv2.imshow('title',dstRotasi)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
# Affine
import cv2
import numpy as np

img = cv2.imread("d:\\Data Kuliah\\Citra Digital - Semester 5\\images2.jpeg")
baris, coloms, ghgh = img.shape

ttkAsal = np.float32([[172,109], [282,65], [272,316]])
ttkTujuan = np.float32([[53,128], [471,46], [275, 385]])

MAffine = cv2.getAffineTransform(ttkAsal, ttkTujuan)

print(MAffine)

dstAffine = cv2.warpAffine(img, MAffine, (coloms, baris))

cv2.imshow('title',dstAffine)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 3.54412955e+00 -6.39676113e-01 -4.86865587e+02]
 [-2.08538830e-01  1.34228929e+00  1.75591461e+01]]
